#ifndef CONSTANTS_H
#define CONSTANTS_H

#ifndef TIME_STEP
#define FPS 30.0
#define TIME_STEP 1/FPS
#endif /* TIME_STEP */

#define ROBOTLEN (7.5/100.0)
#define BALL_RADIUS (0.5*4.27/100.0)
#define BALL_MASS 46e-3
#define ROBOT_MASS 0.6
#define ROBOT_MOMENT_OF_INERTIA (ROBOT_MASS*ROBOTLEN*ROBOTLEN/6.0)
#define ROBOT_MAX_SPEED_PER_WHEEL 0.6

#endif /*CONSTANTS_H*/